##### Fichier de déploiement cPanel ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fmcsproc/futech.fmcspro.ca/Test20250225/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp webpack.config.js $DEPLOYPATH
    - /bin/cp babel.config.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH